### ISSUE TITLE
faceboxSuggestion class not found

### ISSUE THREAD

**Issue by halilemreozen** [bknarendra/fb_photo_friend_finder#3]
Hi Narendra,
Your project looking interesting but when I try to install nokogiri throw a version problem and me kinda strange ruby things. 
I read your code and try on the browser your process but I didn't see any ".faceboxSuggestion" child element in ".fbPhotosPhotoTagboxBase.faceBox" I just add a sample output block, do you have any idea ?

Sample block : 

```
<div class="fbPhotosPhotoTagboxBase faceBox" style="width: 8.5%;height: 11.333333333333%;left: 47.416666666667%;top: 9.3111111111111%;" data-recognizeduids="[]" data-faceboxid="10204125574809305" id="face:10204125574809305">
   <div class="borderTagBox">
      <div class="innerTagBox">
         <div class="ieContentFix">&nbsp;&nbsp;&nbsp;&nbsp;</div>
      </div>
   </div>
   <div class="tag" style="">
      <div class="tagPointer">
         <i class="tagArrow img sp_izBMGoEGKwM_2x sx_bb4b10"></i>
         <div class="tagName"></div>
      </div>
   </div>
</div>
```

**Comment by bknarendra** [comment]
I have seen this issue. It might happen for a photo when FB wasn't able to identify the people. Now it can be because it couldn't recognise the person or the person in question might not be in your friend list.

And as for Nokogiri does your system already have a previous version of nokogiri (If yes you could just provide that version in Gemfile). Could you provide more logs.
